{% set name = "python-iso639" %}
{% set version = "2024.10.22" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 750f21b6a0bc6baa24253a3d8aae92b582bf93aa40988361cd96852c2c6d9a52

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=65.3.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - iso639
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Look-up utilities for ISO 639 language codes and names
  home: https://github.com/jacksonllee/iso639
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
